#!/usr/bin/env bash

cd "$(dirname "$0")"

. ./clear_dist.sh

echo "
    Beginning build of new package version ...
"
cd ..
python3 -m pip install --upgrade pip
pip install --upgrade setuptools build twine

python3 -m build

twine upload --repository testpypi dist/*